web:
  build: .
  ports:
    - "8000:80"
  links:
    - db
  volumes:
    - ./kohana:/var/www/html
db:
  image: "mysql:5"
  volumes:
    - ./mysql:/etc/mysql/conf.d
  environment:
    MYSQL_ROOT_PASSWORD: phpapptest
    MYSQL_DATABASE: phpapp
